"""
轻量 GitLab API 客户端 —— 仅用于 TranzorExporter 从 tranzor-fix 分支
commit diff 中恢复 Language Lead BATCH_FIX 的 pre-fix 原译文。

覆盖的 API：
- list_branches(project_id, search)       列分支
- get_commit(project_id, sha)             取 commit 元数据
- get_commit_diff(project_id, sha)        取 commit unified diff（含缓存）
- get_merge_request(project_id, mr_iid)   取 MR 元数据（含 labels）—— 用于
                                          识别哪些 MR 被打了 ``skip-translate``
                                          这类阻止 Tranzor 翻译流水线的标签

配置来源（优先级）：
1. 环境变量 TRANZOR_GITLAB_TOKEN / TRANZOR_GITLAB_BASE_URL
2. 用户家目录文件 ~/.tranzor_exporter_config.json
"""
import json
import os
import re
from datetime import datetime, timedelta, timezone
from urllib.parse import quote

import requests

CONFIG_PATH = os.path.expanduser("~/.tranzor_exporter_config.json")
DEFAULT_BASE_URL = "https://git.ringcentral.com"


def load_config():
    if os.path.isfile(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                return json.load(f) or {}
        except Exception:
            return {}
    return {}


def save_config(cfg):
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)


def update_config(**kwargs):
    """Merge-update the config file —— 只覆盖传入的 key，保留其它。

    ``save_config`` 是整体覆盖；直接用它写 token 会抹掉同文件里别的
    设置（bridge 端口等）。GUI 的 GitLab 设置对话框用这个增量写。
    值为 ``None`` 的 key 跳过（"不改这一项"）。
    """
    cfg = load_config()
    for k, v in kwargs.items():
        if v is not None:
            cfg[k] = v
    save_config(cfg)
    return cfg


# ---------------------------------------------------------------------------
# 构建时注入的 service-account 凭证（PR-J）
# ---------------------------------------------------------------------------
# 目的：把一个**只读 service account**（非任何个人账号）的 token 在打包
# 时嵌入 EXE，让分发给语言工作者的版本开箱即用、零配置。
#
# ⚠ 安全边界 —— 务必理解：
#   - 下面的 _obfuscate 只是 base64 + 单字节 XOR，**不是加密**。它只挡
#     `strings` 顺手扫描；有意逆向者几分钟即可还原。
#   - 因此嵌入的**必须是最小权限只读 service account**（只 read_api、只
#     加必要的 group），绝不能是个人 PAT。泄露后果仅限"只读若干仓库"，
#     且可独立吊销、不牵连任何个人。
#   - 仅用于内网分发的 EXE。
#
# 嵌入模块 ``gitlab_token_embed.py`` 由 build_windows.ps1 在打包前生成，
# **不进 git**（见 .gitignore）。开发 / CI 环境没有它 → 嵌入凭证为空，
# 一切回退到环境变量 / 配置文件。
_EMBED_XOR_KEY = 0x5A


def _obfuscate(s: str) -> str:
    """base64(xor(utf8(s)))。给 build 脚本生成嵌入模块用。**非加密**。"""
    import base64
    if not s:
        return ""
    xored = bytes(b ^ _EMBED_XOR_KEY for b in s.encode("utf-8"))
    return base64.b64encode(xored).decode("ascii")


def _deobfuscate(s: str) -> str:
    """:func:`_obfuscate` 的逆。坏数据一律返回 "" —— 嵌入凭证损坏绝不能
    让客户端崩。"""
    if not s:
        return ""
    try:
        import base64
        raw = base64.b64decode(s.encode("ascii"))
        return bytes(b ^ _EMBED_XOR_KEY for b in raw).decode("utf-8")
    except Exception:
        return ""


def _read_embedded():
    """读构建时生成的嵌入模块。返回 ``(token, base_url)``；缺失 → ("","")。"""
    try:
        import gitlab_token_embed as _emb
    except Exception:
        return ("", "")
    return (
        _deobfuscate(getattr(_emb, "TOKEN_B64", "") or ""),
        _deobfuscate(getattr(_emb, "BASE_URL_B64", "") or ""),
    )


def write_embedded_credentials(token, base_url="", path=None):
    """生成 ``gitlab_token_embed.py`` —— 由 build_windows.ps1 在打包前调。

    从构建机的环境变量拿到明文 token，混淆后写入模块。生成的文件被
    .gitignore 忽略，绝不进版本库。空 token 时仍写一个空模块（让运行时
    干净地回退），方便构建脚本无脑调用。
    """
    if path is None:
        path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "gitlab_token_embed.py")
    content = (
        '"""AUTO-GENERATED at build time — DO NOT COMMIT, DO NOT EDIT.\n'
        "\n"
        "Holds an obfuscated read-only service-account GitLab credential,\n"
        "regenerated by build_windows.ps1 from build-machine env vars.\n"
        "Obfuscation is base64+XOR (NOT encryption) — the security model\n"
        "relies on this being a minimal read-only service account, not a\n"
        "personal token. See gitlab_client._obfuscate for the rationale.\n"
        '"""\n'
        f"TOKEN_B64 = {_obfuscate(token or '')!r}\n"
        f"BASE_URL_B64 = {_obfuscate(base_url or '')!r}\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


def get_token():
    # 优先级：环境变量 > 用户配置文件 > 构建嵌入 service-account。
    # 这样开发者 / 高级用户用自己的 token 仍优先；分发给语言工作者的
    # EXE 在前两者都空时自动用嵌入的只读凭证（零配置）。
    return (os.getenv("TRANZOR_GITLAB_TOKEN")
            or load_config().get("gitlab_token")
            or _read_embedded()[0]
            or "")


def get_base_url():
    return (os.getenv("TRANZOR_GITLAB_BASE_URL")
            or load_config().get("gitlab_base_url")
            or _read_embedded()[1]
            or DEFAULT_BASE_URL)


def verify_connection(base_url=None, token=None, timeout=10):
    """探测 (base_url, token) 能否连通 GitLab 并通过鉴权。

    用 ``GET /api/v4/user`` —— ``read_api`` scope 即可访问，成功时返回
    当前 token 对应的用户身份，让用户在对话框里确认"连上的是我自己的
    账号"。这个端点也最能区分各类失败：

    Returns dict:
      - 成功：``{"ok": True, "username": ..., "name": ..., "base_url": ...}``
      - 失败：``{"ok": False, "error": "<人话>", "status": <int|None>}``

    永不抛 —— 对话框直接渲染返回的 dict。
    """
    burl = (base_url or get_base_url() or "").rstrip("/")
    tok = token or get_token()
    if not burl:
        return {"ok": False, "error": "Base URL 为空", "status": None}
    if not tok:
        return {"ok": False, "error": "Token 为空", "status": None}
    try:
        resp = requests.get(
            f"{burl}/api/v4/user",
            headers={"PRIVATE-TOKEN": tok},
            timeout=timeout,
        )
    except requests.exceptions.RequestException as e:
        # 连不上 / DNS / 超时 —— 多半是 base_url 写错或没连 VPN。
        return {"ok": False, "error": f"连接失败：{e}", "status": None}

    if resp.status_code == 200:
        try:
            data = resp.json()
        except Exception:
            data = {}
        return {
            "ok": True,
            "username": data.get("username") or "?",
            "name": data.get("name") or "",
            "base_url": burl,
            "status": 200,
        }
    if resp.status_code == 401:
        return {"ok": False, "status": 401,
                "error": "401 未授权 —— Token 无效或已过期"}
    if resp.status_code == 403:
        return {"ok": False, "status": 403,
                "error": "403 禁止 —— Token 权限不足（需要 read_api scope）"}
    if resp.status_code == 404:
        return {"ok": False, "status": 404,
                "error": "404 —— Base URL 可能不是有效的 GitLab 实例"}
    return {"ok": False, "status": resp.status_code,
            "error": f"HTTP {resp.status_code}"}


# ---------------------------------------------------------------------------
# HTTP client
# ---------------------------------------------------------------------------
class GitLabClient:
    def __init__(self, base_url=None, token=None, timeout=30):
        self.base_url = (base_url or get_base_url()).rstrip("/")
        self.token = token or get_token()
        self.timeout = timeout
        self._session = requests.Session()
        if self.token:
            self._session.headers["PRIVATE-TOKEN"] = self.token
        self._commit_diff_cache = {}   # sha -> diff list
        self._branches_cache = {}      # (project_id, search) -> branches list
        self._mr_cache = {}            # (project_id, mr_iid) -> mr dict

    def has_token(self):
        return bool(self.token)

    def _encode(self, s):
        return quote(s, safe="")

    def list_branches(self, project_id, search=None, max_pages=50):
        """List branches, paginating until exhausted (capped at ``max_pages``).

        Previously hard-coded to the first 3 pages (300 branches), which silently
        truncated long-lived ``tranzor-fix`` histories. Now walks until an empty
        / partial page is returned, with ``max_pages`` (default 50 → 5000) as a
        runaway safety cap.
        """
        key = (project_id, search or "")
        if key in self._branches_cache:
            return self._branches_cache[key]

        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/repository/branches")
        results = []
        for page in range(1, max_pages + 1):
            params = {"per_page": 100, "page": page}
            if search:
                params["search"] = search
            resp = self._session.get(url, params=params, timeout=self.timeout)
            resp.raise_for_status()
            batch = resp.json() or []
            results.extend(batch)
            if len(batch) < 100:
                break
        self._branches_cache[key] = results
        return results

    def get_commit(self, project_id, sha):
        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/repository/commits/{sha}")
        resp = self._session.get(url, timeout=self.timeout)
        resp.raise_for_status()
        return resp.json()

    def get_commit_diff(self, project_id, sha):
        if sha in self._commit_diff_cache:
            return self._commit_diff_cache[sha]
        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/repository/commits/{sha}/diff")
        resp = self._session.get(url, timeout=self.timeout)
        resp.raise_for_status()
        data = resp.json() or []
        self._commit_diff_cache[sha] = data
        return data

    def get_file_raw(self, project_id, path, ref):
        """取某文件在指定 ``ref``（commit sha / 分支名）下的原始全文。

        UNS 整文件模板需要这条：fix 提交把整份 ``.hbs`` 覆写，commit diff
        默认只带 3 行上下文，无法重建 8KB 全文 —— 必须直接拉 blob。

        Returns:
            str 文件内容；``404``（该 ref 下文件不存在，例如新增文件没有
            parent 版本）返回 ``None``。

        Note:
            ``repository/files/.../raw`` 的项目级 401/403 仍会经
            ``raise_for_status`` 抛 ``requests.HTTPError``；文件级 404 这里
            吞掉返回 ``None``（调用方据此回退到其它 pre/post 来源）。缓存
            按 ``(project_id, path, ref)`` 复用，避免同一文件重复拉取。
        """
        if not path or not ref:
            return None
        cache_key = (str(project_id), str(path), str(ref))
        if not hasattr(self, "_file_raw_cache"):
            self._file_raw_cache = {}
        if cache_key in self._file_raw_cache:
            return self._file_raw_cache[cache_key]
        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/repository/files/"
               f"{self._encode(path)}/raw")
        resp = self._session.get(url, params={"ref": ref}, timeout=self.timeout)
        if resp.status_code == 404:
            self._file_raw_cache[cache_key] = None
            return None
        resp.raise_for_status()
        text = resp.text
        self._file_raw_cache[cache_key] = text
        return text

    def get_merge_request(self, project_id, mr_iid):
        """Fetch full MR metadata from GitLab.

        Returns the raw ``GET /api/v4/projects/:id/merge_requests/:iid``
        response dict — its ``labels`` field is the only thing my-tools
        cares about today (Tranzor Platform's ``SKIP_TRANSLATE_LABEL``
        machinery, default ``skip-translate``, lives entirely in GitLab
        labels per LOC-skip / commit ``8663a18``).

        Cached per ``(project_id, mr_iid)`` for the lifetime of this
        client instance — a Tranzor Checks sync touches each MR exactly
        once, but the cache shields us if the same MR is referenced by
        multiple ``task_checks`` rows (rare but possible).

        Raises on HTTP error so callers can decide whether to swallow
        the failure (typical: store ``""`` to signal "we tried, no data")
        or surface it. The Tranzor Checks sync path swallows: missing
        labels must never tank an otherwise healthy sync.
        """
        key = (str(project_id), int(mr_iid))
        if key in self._mr_cache:
            return self._mr_cache[key]
        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/merge_requests/{int(mr_iid)}")
        resp = self._session.get(url, timeout=self.timeout)
        resp.raise_for_status()
        data = resp.json() or {}
        self._mr_cache[key] = data
        return data

    def fetch_mr_labels(self, project_id, mr_iid):
        """Convenience wrapper returning ``mr['labels']`` as ``list[str]``.

        Failures bubble up; the typical caller (Tranzor Checks sync) wraps
        this in try/except so a single 404 doesn't kill the batch.
        """
        mr = self.get_merge_request(project_id, mr_iid)
        labels = mr.get("labels") or []
        return [str(x) for x in labels if x]

    def list_commits(self, project_id, *, ref_name=None, since=None,
                     until=None, author=None, per_page=100, max_pages=5):
        """List commits with optional ref / time / author filters.

        Drives BATCH_FIX detection in task_post_edit. We pass through to
        GitLab's ``GET /projects/:id/repository/commits`` and let the
        server do as much filtering as it can:

        - ``ref_name`` is **critical** for finding BATCH_FIX commits on
          MR source branches. Without it the API only returns commits on
          the project's default branch and feature-branch BATCH_FIX
          commits are silently invisible.
        - ``author`` is a server-side filter on author email. Verified
          against the platform — uses substring match, so passing the
          full email is precise enough.
        - ``since`` / ``until`` are ISO-8601 strings.

        Returns the concatenated commit list across pages, capped at
        ``max_pages`` (default 5 → 500 commits) to keep memory bounded
        on long-lived branches. The cap is well above realistic
        BATCH_FIX volume (a project sees ≤ ~10 BATCH_FIX commits a day
        at peak).

        Cached per parameter tuple for the lifetime of this client
        instance; consecutive checks against the same branch don't
        repeat the HTTP round-trip.
        """
        key = (
            str(project_id), ref_name or "", since or "",
            until or "", author or "",
        )
        if not hasattr(self, "_commits_cache"):
            self._commits_cache = {}
        if key in self._commits_cache:
            return self._commits_cache[key]

        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/repository/commits")
        out = []
        for page in range(1, max_pages + 1):
            params = {"per_page": per_page, "page": page}
            if ref_name:
                params["ref_name"] = ref_name
            if since:
                params["since"] = since
            if until:
                params["until"] = until
            if author:
                params["author"] = author
            r = self._session.get(url, params=params, timeout=self.timeout)
            r.raise_for_status()
            batch = r.json() or []
            out.extend(batch)
            if len(batch) < per_page:
                break
        self._commits_cache[key] = out
        return out

    def list_mr_commits(self, project_id, mr_iid, *, per_page=100, max_pages=2):
        """List a merge request's own commits via
        ``GET /merge_requests/:iid/commits`` (newest-first).

        One round-trip that replaces the ``get_merge_request`` (to learn the
        source branch) + ``list_commits(ref_name=branch)`` pair the post-edit
        BATCH_FIX probe used to need — halving GitLab latency per MR, which is
        the dominant cost of the "✏️ Post-edited only" filter. The Tranzor
        Language Lead fix commit is always the newest Tranzor-authored commit,
        so page 1 (per_page=100) reliably contains it; we read up to
        ``max_pages`` for safety. Cached per ``(project_id, mr_iid)``.
        """
        key = (str(project_id), int(mr_iid))
        if not hasattr(self, "_mr_commits_cache"):
            self._mr_commits_cache = {}
        if key in self._mr_commits_cache:
            return self._mr_commits_cache[key]
        url = (f"{self.base_url}/api/v4/projects/"
               f"{self._encode(project_id)}/merge_requests/{int(mr_iid)}/commits")
        out = []
        for page in range(1, max_pages + 1):
            r = self._session.get(
                url, params={"per_page": per_page, "page": page},
                timeout=self.timeout)
            r.raise_for_status()
            batch = r.json() or []
            out.extend(batch)
            if len(batch) < per_page:
                break
        self._mr_commits_cache[key] = out
        return out


# ---------------------------------------------------------------------------
# Fix-commit discovery
# ---------------------------------------------------------------------------
BRANCH_TS_RE = re.compile(r"(\d{14})(?:[^\d]|$)")  # trailing YYYYMMDDHHMMSS


def parse_branch_timestamp(branch_name):
    """``tranzor-fix/26-2-2_XMN/20260417070703`` -> naive datetime."""
    m = BRANCH_TS_RE.search(branch_name or "")
    if not m:
        return None
    try:
        return datetime.strptime(m.group(1), "%Y%m%d%H%M%S")
    except ValueError:
        return None


def _parse_fixed_at(fixed_at_iso):
    """Tolerant ISO-8601 parse; returns naive datetime in UTC terms."""
    if not fixed_at_iso:
        return None
    s = fixed_at_iso
    if s.endswith("Z"):
        s = s[:-1]
    # Strip any fractional seconds / timezone suffix
    s = re.split(r"[+\-]\d{2}:?\d{2}$", s)[0]
    s = s.split(".", 1)[0]
    try:
        return datetime.fromisoformat(s)
    except ValueError:
        try:
            return datetime.strptime(s, "%Y-%m-%d %H:%M:%S")
        except ValueError:
            return None


class GitLabAccessError(Exception):
    """Raised when GitLab returns 401/403/404 on project-scoped endpoints —
    typically means the PAT user is not a member of the target project.
    """
    def __init__(self, project_id, status_code, url=None):
        self.project_id = project_id
        self.status_code = status_code
        self.url = url
        super().__init__(
            f"GitLab access denied for project '{project_id}' "
            f"(HTTP {status_code}). Likely the PAT user lacks membership.")


def _candidate_branches_within_window(client, project_id, fixed_at_iso,
                                      window_minutes):
    """Return branches whose name timestamp is within ``window_minutes`` of
    ``fixed_at_iso``, sorted by absolute time-delta ascending.

    Common helper for both the legacy time-only matcher and the new key-aware
    matcher. Raises :class:`GitLabAccessError` on 401/403/404 from listing.
    """
    fixed_at = _parse_fixed_at(fixed_at_iso)
    if not fixed_at:
        return []
    try:
        branches = client.list_branches(project_id, search="tranzor-fix")
    except requests.HTTPError as e:
        code = getattr(e.response, "status_code", None)
        if code in (401, 403, 404):
            raise GitLabAccessError(project_id, code,
                                    url=getattr(e.response, "url", None)) from e
        raise

    window = timedelta(minutes=window_minutes)
    candidates = []
    for b in branches:
        ts = parse_branch_timestamp(b.get("name", ""))
        if not ts:
            continue
        delta = abs(ts - fixed_at)
        if delta <= window:
            candidates.append((delta, b))
    candidates.sort(key=lambda x: x[0])
    return [b for _delta, b in candidates]


def find_fix_commit_sha(client, project_id, fixed_at_iso,
                       window_minutes=60):
    """Legacy time-only matcher — returns the closest-by-time ``tranzor-fix``
    branch HEAD SHA within ``window_minutes``.

    .. deprecated::
        In batch-fix scenarios many cases share near-identical ``fixed_at``,
        and time-min alone can pick a sibling fix's commit → silent wrong-fill
        downstream. Prefer :func:`find_fix_commit_for_key`, which iterates
        candidates ordered by time-delta and verifies that the chosen diff
        actually edits the target ``(opus_id, target_language)``.

    Raises:
        GitLabAccessError: PAT lacks read access on the project (401/403/404).
    """
    candidates = _candidate_branches_within_window(
        client, project_id, fixed_at_iso, window_minutes)
    if not candidates:
        return None
    commit = candidates[0].get("commit") or {}
    return commit.get("id")


def find_fix_commit_for_key(client, project_id, fixed_at_iso,
                            opus_id, target_language, window_minutes=60):
    """Find the ``tranzor-fix`` commit that actually edits
    ``(opus_id, target_language)``.

    Walks all candidate branches whose name timestamp is within
    ``window_minutes`` of ``fixed_at_iso``, ordered by absolute time-delta
    ascending. For each candidate, fetches its diff and runs
    :func:`extract_diff_values`. Returns the first candidate whose diff
    actually contains the target key for the target language.

    This guards against the batch-fix silent-fill scenario: when many cases
    share near-identical ``fixed_at`` (e.g. repeated-string mass fixes),
    matching purely by time-delta can pick a sibling fix's commit, and the
    downstream diff parser would either return ``(None, None)`` (silent skip)
    or — worse — pick up an unrelated occurrence of the key.

    Returns:
        (sha, pre, post): commit SHA + diff '-' / '+' values when a candidate's
        diff contains the key. ``(None, None, None)`` if no candidate matched
        (no branches in window, or none of their diffs touched the key).

    Raises:
        GitLabAccessError: PAT lacks read access on the project (401/403/404).
    """
    candidates = _candidate_branches_within_window(
        client, project_id, fixed_at_iso, window_minutes)
    for b in candidates:
        sha = (b.get("commit") or {}).get("id")
        if not sha:
            continue
        try:
            diff = client.get_commit_diff(project_id, sha)
        except Exception:
            # Diff fetch failure on one candidate shouldn't abort the search —
            # later candidates may still match.
            continue
        pre, post = extract_diff_values(diff, opus_id, target_language)
        if pre is not None or post is not None:
            return sha, pre, post
    return None, None, None


# ---------------------------------------------------------------------------
# Diff parser — 提取某个 (opus_id, target_language) 的 pre/post 文本
# ---------------------------------------------------------------------------
def _lang_path_variants(lang):
    variants = {lang}
    if "-" in lang:
        variants.add(lang.replace("-", "_"))
        variants.add(lang.replace("-", "."))
        variants.add(lang.lower())
    # 大部分 RC 项目资源文件走 zh-CN / zh_CN / zh-cn 三种其一
    return variants


def _key_last_segment(opus_id):
    if not opus_id:
        return ""
    return opus_id.rsplit(".", 1)[-1]


def _unescape_generic(s):
    """通用转义还原 —— 覆盖 JSON/JS/Python 字符串里最常见的转义序列。"""
    if not s:
        return s
    return (s.replace("\\\\", "\x00")  # 占位保护真实反斜杠
             .replace("\\n", "\n")
             .replace("\\r", "\r")
             .replace("\\t", "\t")
             .replace("\\'", "'")
             .replace('\\"', '"')
             .replace("\x00", "\\"))


# 针对常见 i18n 格式的取值正则；用 {key} 占位符，稍后替换为实际 key。
# 顺序决定优先级 —— 把最严格的放前面。
_VALUE_PATTERN_TEMPLATES = [
    # JSON:           "KEY" : "VALUE"     (VALUE 可含 \" \\ 转义)
    r'"{key}"\s*:\s*"((?:[^"\\]|\\.)*)"',
    # .strings:       "KEY" = "VALUE";
    r'"{key}"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;',
    # JS/TS 对象字面量，单引号：  KEY: 'VALUE'   或   'KEY': 'VALUE'
    r'(?:^|[\s{{\[,])\'?{key}\'?\s*:\s*\'((?:[^\'\\]|\\.)*)\'',
    # JS/TS 对象字面量，双引号：  KEY: "VALUE"   或   "KEY": "VALUE"
    r'(?:^|[\s{{\[,])"?{key}"?\s*:\s*"((?:[^"\\]|\\.)*)"',
    # YAML:           KEY: "VALUE"
    r'(?:^|\s){key}\s*:\s*"((?:[^"\\]|\\.)*)"',
    # properties:     KEY=VALUE           (行尾无引号，吃到行尾或逗号前)
    r'(?:^|\s){key}\s*=\s*([^\n\r]+?)\s*,?\s*$',
]


def _compile_value_regexes(key):
    key_re = re.escape(key)
    return [re.compile(t.replace("{key}", key_re))
            for t in _VALUE_PATTERN_TEMPLATES]


def _extract_value_from_line(line_body, value_regexes):
    for r in value_regexes:
        m = r.search(line_body)
        if m:
            return _unescape_generic(m.group(1))
    return None


def extract_diff_values(commit_diff, opus_id, target_language):
    """在 commit_diff 中定位 (opus_id, target_language) 的 pre/post 文本。

    Args:
        commit_diff: GitLab ``/commits/:sha/diff`` 返回的 list
        opus_id: Tranzor 的 opus_id（末段为 key）
        target_language: 目标语言码，用来过滤 diff 中的文件路径

    Returns:
        (pre_text, post_text) 元组；任何一端取不到则为 None。
    """
    key = _key_last_segment(opus_id)
    if not key:
        return None, None

    lang_frags = _lang_path_variants(target_language)
    value_regexes = _compile_value_regexes(key)

    for file_diff in commit_diff or []:
        path = (file_diff.get("new_path")
                or file_diff.get("old_path")
                or "")
        if not any(frag in path for frag in lang_frags):
            continue
        patch = file_diff.get("diff") or ""

        pre = post = None
        for line in patch.splitlines():
            if not line:
                continue
            if line.startswith("---") or line.startswith("+++"):
                continue
            if line[0] not in ("-", "+"):
                continue
            if key not in line:
                continue
            body = line[1:]
            val = _extract_value_from_line(body, value_regexes)
            if val is None:
                continue
            if line[0] == "-" and pre is None:
                pre = val
            elif line[0] == "+" and post is None:
                post = val
            if pre is not None and post is not None:
                return pre, post
        if pre is not None or post is not None:
            return pre, post

    return None, None


# ---------------------------------------------------------------------------
# MR 源分支 Language Lead fix 提交扫描（独立于 fixed_by_lead）
#
# 背景：detect_mr_changes 现有的 fix 恢复（find_fix_commit_for_key）面向
# ``tranzor-fix/<timestamp>`` 分支 + key-value 资源文件，且整条以
# ``fixed_by_lead`` 非空为前提。但 Tranzor 的 fix endpoint 把审计写在整条
# git 提交链的最后（commit 在前、写库在后、无重试），任一步失败就只提交了
# GitLab 却把 ``fixed_by_lead`` 留成 NULL；BATCH_FIX 路径更是根本不写该
# 字段。这两类「已提交 GitLab 但 DB 无痕」的 post-edit 会被 Changes 报告
# 整条漏掉。本节直接扫描 **MR 源分支** 上 Tranzor 服务账号推送的 Language
# Lead fix 提交（单条 + 批量），独立重建 (opus_id, lang) 的 pre/post。
# UNS 整文件模板走「路径 → key」映射 + blob 取全文；普通 key-value 资源
# 文件回退到既有 extract_diff_values。
# ---------------------------------------------------------------------------

# Tranzor 后端推送 Language Lead fix 提交时的服务账号与标题指纹，见
# app/utils/commit_message.py: build_language_lead_fix_commit_message /
# build_language_lead_batch_fix_commit_message。task_post_edit.py 里另有
# 同值的服务账号常量（BATCH_FIX 布尔检测）；两处独立模块刻意不交叉 import
# 以免环依赖。
LEAD_FIX_AUTHOR_EMAIL = "tranzor.service@rcoffice.ringcentral.com"
_LEAD_FIX_TITLE_SINGLE = "[Tranzor] Language Lead fix"
_LEAD_FIX_TITLE_BATCH = "[Tranzor] Language Lead batch fix"
_LEAD_FIX_LOOKBACK_DAYS = 30

# UNS 模板根 → 命名空间，镜像 export_import_cli UnsTemplateRootParser。
_UNS_TEMPLATE_ROOTS = (
    ("uns-app/templateStorage/", "common.uns"),
    ("uns-app/newTemplateStorage/", "common.uns.new"),
)
_UNS_PARTIALS_DIR = "_partials/"
_UNS_PARTIALS_NS = ".partials"


def is_lead_fix_commit(commit):
    """True iff ``commit`` 是 Tranzor 推送的 Language Lead fix 提交。

    严格双重判定：作者邮箱 == 服务账号 且 标题命中单条 / 批量 fix 前缀。
    与 task_post_edit._is_batch_fix_commit 同源，但这里同时覆盖单条
    ``[Tranzor] Language Lead fix: <lang> - <opus_id>`` 与批量
    ``[Tranzor] Language Lead batch fix: N translation(s)``。
    """
    if not isinstance(commit, dict):
        return False
    if (commit.get("author_email") or "") != LEAD_FIX_AUTHOR_EMAIL:
        return False
    title = commit.get("title") or ""
    return (title.startswith(_LEAD_FIX_TITLE_SINGLE)
            or title.startswith(_LEAD_FIX_TITLE_BATCH))


def mr_has_lead_fix_commit(client, project_id, mr_iid):
    """True iff the MR carries a Tranzor Language Lead fix commit (single OR
    batch) — the fast post-edit signal.

    One GitLab round-trip via the MR's own commits, so it works regardless of
    the source-branch name and without a separate get_merge_request lookup.
    Catches both single-row and batch fixes (``is_lead_fix_commit`` matches
    both title forms), unlike the old branch scan which only fingerprinted
    batch fixes. Raises ``GitLabAccessError`` on 401/403/404 so the caller can
    give up on a project the PAT can't read.
    """
    if not project_id or mr_iid is None:
        return False
    try:
        commits = client.list_mr_commits(project_id, int(mr_iid))
    except requests.HTTPError as e:
        code = getattr(e.response, "status_code", None)
        if code in (401, 403, 404):
            raise GitLabAccessError(project_id, code,
                                    url=getattr(e.response, "url", None)) from e
        raise
    return any(is_lead_fix_commit(c) for c in (commits or []))


def parse_uns_template_path(path):
    """``uns-app/templateStorage/<feature>/<feature>__<type>__<brand>__<locale>.hbs``
    → ``(opus_id, target_language)``；非 UNS 模板路径返回 ``None``。

    镜像 export_import_cli 的 UnsKeyStrategy / UnsTemplateRootParser：
    opus_id = ``<namespace>.<feature>__<type>__<brand>``，locale 的下划线
    还原为连字符（``fr_CA`` → ``fr-CA``）。``_partials/`` 子目录命名空间
    追加 ``.partials``。
    """
    if not path:
        return None
    dir_prefix = None
    namespace = None
    for root_dir, root_ns in _UNS_TEMPLATE_ROOTS:
        if path.startswith(root_dir):
            remainder0 = path[len(root_dir):]
            if remainder0.startswith(_UNS_PARTIALS_DIR):
                dir_prefix = root_dir + _UNS_PARTIALS_DIR
                namespace = root_ns + _UNS_PARTIALS_NS
            else:
                dir_prefix = root_dir
                namespace = root_ns
            break
    if dir_prefix is None:
        return None

    remainder = path[len(dir_prefix):]
    segments = remainder.split("/")
    if len(segments) != 2:
        return None
    feature, filename = segments
    prefix = feature + "__"
    if (not feature or not filename.startswith(prefix)
            or not filename.endswith(".hbs")):
        return None
    file_body = filename[len(prefix):-len(".hbs")]
    parts = file_body.split("__")
    if len(parts) != 3:
        return None
    type_format, brand, locale = parts
    if not type_format or not brand or not locale:
        return None
    opus_id = f"{namespace}.{feature}__{type_format}__{brand}"
    target_language = locale.replace("_", "-")
    return opus_id, target_language


def _operator_from_fix_title(title):
    """从 es_format 提交标题里抽操作者邮箱（``... | Language Lead <email>
    fix | ...``）；legacy 标题不含操作者身份，返回 ""。"""
    if not title:
        return ""
    m = re.search(r"Language Lead\s+(\S+@\S+?)\s+(?:batch\s+)?fix", title)
    return m.group(1) if m else ""


def _merge_branch_fix(result, key, pre, post, sha, committed_at, title):
    """累积同一 key 跨多个 fix 提交的变更：保留最旧的 pre、采用最新的 post
    （调用方按提交时间升序遍历，故首见即最旧）。"""
    fixed_by = _operator_from_fix_title(title)
    existing = result.get(key)
    if existing is None:
        result[key] = {
            "pre": pre or "",
            "post": post or "",
            "sha": sha,
            "committed_at": committed_at,
            "title": title,
            "fixed_by": fixed_by,
        }
        return
    # 旧→新遍历：pre 保留首见（最旧），post / sha / committed_at 取最新非空。
    if post:
        existing["post"] = post
    existing["sha"] = sha
    existing["committed_at"] = committed_at
    existing["title"] = title
    if fixed_by:
        existing["fixed_by"] = fixed_by


def _list_lead_fix_commits(client, project_id, source_branch, *,
                           lookback_days=_LEAD_FIX_LOOKBACK_DAYS):
    """列出源分支上、回溯窗口内、Tranzor 服务账号推送的 fix 提交，按提交
    时间升序（旧→新）。访问受限（401/403/404）抛 GitLabAccessError。"""
    since_iso = (datetime.now(timezone.utc)
                 - timedelta(days=lookback_days)).isoformat()
    try:
        commits = client.list_commits(
            project_id, ref_name=source_branch, since=since_iso,
            author=LEAD_FIX_AUTHOR_EMAIL)
    except requests.HTTPError as e:
        code = getattr(e.response, "status_code", None)
        if code in (401, 403, 404):
            raise GitLabAccessError(project_id, code,
                                    url=getattr(e.response, "url", None)) from e
        raise
    fixes = [c for c in (commits or []) if is_lead_fix_commit(c)]
    fixes.sort(key=lambda c: c.get("committed_date") or c.get("created_at") or "")
    return fixes


def scan_branch_fix_commits(client, project_id, source_branch, cases_by_key,
                            *, lookback_days=_LEAD_FIX_LOOKBACK_DAYS):
    """扫描 MR 源分支上 Tranzor 的 Language Lead fix 提交，重建每个
    ``(opus_id, target_language)`` 的 pre/post —— **独立于 fixed_by_lead**。

    仅回填出现在 ``cases_by_key`` 里的 (opus_id, lang)，既避免把无关文件 /
    旁支 key 带进报告，也把 blob 拉取限制在本 MR 的翻译单元内。

    Args:
        client: GitLabClient（或等价 duck-type；需 list_commits /
            get_commit_diff / get_file_raw）。
        cases_by_key: ``{(opus_id, target_language): case}``，限定范围 +
            供普通资源文件做 key 回退匹配。None 视为空 dict。

    Returns:
        ``{(opus_id, target_language): {"pre", "post", "sha",
        "committed_at", "title", "fixed_by"}}``。访问受限抛
        ``GitLabAccessError``；单点 diff / blob 失败就地跳过，不影响其它。
    """
    result = {}
    if not project_id or not source_branch:
        return result
    cases_by_key = cases_by_key or {}

    fixes = _list_lead_fix_commits(
        client, project_id, source_branch, lookback_days=lookback_days)

    for commit in fixes:
        sha = commit.get("id")
        if not sha:
            continue
        parents = commit.get("parent_ids") or []
        parent_sha = parents[0] if parents else None
        committed_at = (commit.get("committed_date")
                        or commit.get("created_at") or "")
        title = commit.get("title") or ""
        try:
            diff = client.get_commit_diff(project_id, sha)
        except Exception:
            continue

        for file_diff in diff or []:
            path = (file_diff.get("new_path")
                    or file_diff.get("old_path") or "")
            if not path:
                continue

            uns = parse_uns_template_path(path)
            if uns is not None:
                if uns not in cases_by_key:
                    continue  # 只回填本 MR 已跟踪的单元
                post = pre = None
                try:
                    post = client.get_file_raw(project_id, path, sha)
                except Exception:
                    post = None
                if parent_sha:
                    try:
                        pre = client.get_file_raw(project_id, path, parent_sha)
                    except Exception:
                        pre = None
                _merge_branch_fix(result, uns, pre, post, sha,
                                  committed_at, title)
                continue

            # 普通 key-value 资源文件：对范围内、语言路径匹配的 key 走既有
            # diff 解析（覆盖非 UNS 项目同样的 fixed_by_lead=NULL 漏报）。
            for key in cases_by_key:
                opus_id, lang = key
                if not any(frag in path for frag in _lang_path_variants(lang)):
                    continue
                pre, post = extract_diff_values([file_diff], opus_id, lang)
                if pre is None and post is None:
                    continue
                _merge_branch_fix(result, key, pre, post, sha,
                                  committed_at, title)

    return result
